modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="discordsync"
version="${file.jarVersion}"
displayName="DiscordSync"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/AeonLucid/DiscordSync"
authors="AeonLucid"
description='''
Cross chatting between Minecraft and a Discord channel.
'''

[[dependencies.discordsync]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.discordsync]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"
